kind: pipeline
name: hexo build
type: docker

steps:
  - name: generate blog
    image: node:alpine3.10
    volumes:
      - name: cache
        path: /data
    environment:
      ssh_priv:
        from_secret: priv_key
    commands:
      - "echo ===FETCH DEPENDENCY==="
      - "npm --version"
      - "npm install -g hexo"
      - "npm install"
      - "apk add --no-cache git"
      - "git version"
      - "git submodule init && git submodule update"
      - "echo ===GENERATING==="
      - "hexo generate"
      - "cp -r public /data"
      - "cd /data/public"
      - "git init && git add --all && git commit -m 'updated blog'"

  - name: publish
    image: appleboy/drone-git-push
    volumes:
      - name: cache
        path: /data
    settings:
      branch: master
      remote: git@github.com:Avimitin/avimitin.github.io.git
      ssh_key:
        from_secret: ssh_priv_key
      path: /data/public
      force: true
      author_name: 'avimitin'
      author_email: 'avimitin@gmail.com'

volumes:
  - name: cache
    temp: {}
