baseURL = 'https://blog.sh1mar.in'
languageCode = 'en-us'
title = "sh1marin's Blog"
theme = "paper"
copyright = "Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
hasCJKLanguage = true

[params]
  twitter="sh1ma_rin"
  github="Avimitin"

[menu]
[[menu.main]]
  name = 'RSS'
  url = 'https://blog.sh1mar.in/index.xml'
