baseURL = 'https://blog.sh1mar.in'
languageCode = 'zh'
title = "sh1marin's blog"
theme = "paper"
copyright = "Copyright © 2019-2024, Avimitin and the sh1mar.in; all rights reserved."
hasCJKLanguage = true
paginate = 8

[params]
  color = "linen"
  github="Avimitin"
  rss = true
  monoDarkIcon = true
  math = true

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style='gruvbox'
tabWidth=2
