name: Hugo Deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        env:
          USER: 'BlogGenerator'
          EMAIL: 'avimitin@gmail.com'
          REPO: 'github.com/Avimitin/blog'
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name $USER
          git config --global user.email $EMAIL
          cd public && git init -b gh-pages && git add .
          git commit -m "Generate static blog"
          git push --force "https://$TOKEN@$REPO" gh-pages:gh-pages
